apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: oispdevicesmanagers.oisp.net
spec:
  group: oisp.net
  names:
    kind: OispDevicesManager
    listKind: OispDevicesManagerList
    plural: oispdevicesmanagers
    singular: oispdevicesmanager
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            podTemplateSpec:
              description: PodTemplate for every plugin deployment
              type: object
            watchAnnotationKey:
              description: annotation name which contains the device resource description
              type: string
            watchLabelKey:
              description: Label name to identify oisp-managed nodes
              type: string
            watchLabelValue:
              description: Label value
              type: string
          required:
          - watchLabelKey
          - watchLabelValue
          - watchAnnotationKey
          - podTemplateSpec
          type: object
        status:
          properties:
            phase:
              description: State of the CRD owning operator
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
