apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-watcher
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oispdevicesmanager-watcher
rules:
- apiGroups:
  - oisp.net
  resources:
  - oispdevicesmanagers
  verbs:
  - get
  - list
  - watch
