apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-watcher
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oispdevicesmanager-watcher
rules:
- apiGroups:
  - oisp.net
  - apps
  resources:
  - oispdevicesmanagers
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
  - create
