apiVersion: apps/v1
kind: Deployment
metadata:
  name: oisp-devices-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: oisp-devices-operator
  template:
    metadata:
      labels:
        name: oisp-devices-operator
    spec:
      serviceAccountName: oisp-devices-operator
      containers:
        - name: oisp-devices-operator
          # Replace this with the built image name
          image: docker.io/wagmarcel/oisp-devices-operator:v0.1
          command:
          - oisp-devices-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "oisp-devices-operator"
