// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/oisp-devices-operator/pkg/apis/oisp/v1alpha1.OispDevicesManager":       schema_pkg_apis_oisp_v1alpha1_OispDevicesManager(ref),
		"github.com/oisp-devices-operator/pkg/apis/oisp/v1alpha1.OispDevicesManagerSpec":   schema_pkg_apis_oisp_v1alpha1_OispDevicesManagerSpec(ref),
		"github.com/oisp-devices-operator/pkg/apis/oisp/v1alpha1.OispDevicesManagerStatus": schema_pkg_apis_oisp_v1alpha1_OispDevicesManagerStatus(ref),
	}
}

func schema_pkg_apis_oisp_v1alpha1_OispDevicesManager(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "OispDevicesManager is the Schema for the oispdevicesmanagers API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/oisp-devices-operator/pkg/apis/oisp/v1alpha1.OispDevicesManagerSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/oisp-devices-operator/pkg/apis/oisp/v1alpha1.OispDevicesManagerStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/oisp-devices-operator/pkg/apis/oisp/v1alpha1.OispDevicesManagerSpec", "github.com/oisp-devices-operator/pkg/apis/oisp/v1alpha1.OispDevicesManagerStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_oisp_v1alpha1_OispDevicesManagerSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "OispDevicesManagerSpec defines the desired state of OispDevicesManager",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_oisp_v1alpha1_OispDevicesManagerStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "OispDevicesManagerStatus defines the observed state of OispDevicesManager",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
